// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoundRent.Api.Infrastructure.Data;

#nullable disable

namespace SoundRent.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.AccessorySerialInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<int>("PhysicalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SerialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentType", "PhysicalStatus")
                        .HasDatabaseName("IX_AccessorySerialInventory_Type_PhysicalStatus");

                    b.HasIndex("EquipmentType", "SerialCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessorySerialInventory_Type_Code");

                    b.ToTable("AccessorySerialInventory", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BlockedDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("SystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_BlockedDates_EndDate");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_BlockedDates_StartDate");

                    b.HasIndex("SystemType")
                        .HasDatabaseName("IX_BlockedDates_SystemType");

                    b.ToTable("BlockedDates", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_Books_SortOrder");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("IX_Books_Title");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_BookCopies_BookId");

                    b.HasIndex("BookId", "CopyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_BookCopies_BookId_CopyNumber");

                    b.ToTable("BookCopies", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deposit")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HebrewLentDisplay")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("HebrewReturnedDisplay")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LentAt")
                        .HasDatabaseName("IX_BookLoans_LentAt");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_BookLoans_Phone");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("IX_BookLoans_ReturnedAt");

                    b.ToTable("BookLoans", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookLoanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("BookLoanId")
                        .HasColumnType("integer");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HebrewReturnedDisplay")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_BookLoanItems_BookId");

                    b.HasIndex("BookLoanId")
                        .HasDatabaseName("IX_BookLoanItems_BookLoanId");

                    b.HasIndex("CopyNumber")
                        .HasDatabaseName("IX_BookLoanItems_CopyNumber");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("IX_BookLoanItems_ReturnedAt");

                    b.ToTable("BookLoanItems", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Customer", b =>
                {
                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Phone1");

                    b.HasIndex("Phone2")
                        .HasDatabaseName("IX_Customers_Phone2")
                        .HasFilter("\"Phone2\" IS NOT NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Customers_UpdatedAt");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.CustomerDebt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("BookLoanItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Deposit")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("SourceOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ToolLoanItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookLoanItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerDebts_BookLoanItemId");

                    b.HasIndex("ChargedAt")
                        .HasDatabaseName("IX_CustomerDebts_ChargedAt");

                    b.HasIndex("IsPaid")
                        .HasDatabaseName("IX_CustomerDebts_IsPaid");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_CustomerDebts_Phone");

                    b.HasIndex("SessionKey")
                        .HasDatabaseName("IX_CustomerDebts_SessionKey");

                    b.HasIndex("ToolLoanItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerDebts_ToolLoanItemId");

                    b.ToTable("CustomerDebts", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.CustomerSystem", b =>
                {
                    b.Property<string>("CustomerPhone1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SystemType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CustomerPhone1", "SystemType");

                    b.HasIndex("SystemType")
                        .HasDatabaseName("IX_CustomerSystems_SystemType");

                    b.ToTable("CustomerSystems", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMaintenanceMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("EquipmentType")
                        .IsUnique()
                        .HasDatabaseName("IX_Equipments_EquipmentType_Unique");

                    b.ToTable("Equipments", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.EquipmentDefaultAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessoryEquipmentType")
                        .HasColumnType("integer");

                    b.Property<string>("AccessorySerialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InventoryDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentEquipmentType")
                        .HasColumnType("integer");

                    b.Property<string>("ParentSerialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryDefinitionId")
                        .HasDatabaseName("IX_EquipmentDefaultAccessories_InventoryDefinitionId");

                    b.HasIndex("ParentEquipmentType", "ParentSerialCode")
                        .HasDatabaseName("IX_EquipmentDefaultAccessories_ParentUnit");

                    b.HasIndex("ParentEquipmentType", "ParentSerialCode", "InventoryDefinitionId", "AccessorySerialCode")
                        .IsUnique()
                        .HasDatabaseName("IX_EquipmentDefaultAccessories_ParentUnit_Def_Code");

                    b.ToTable("EquipmentDefaultAccessories", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.EquipmentDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsMaintenanceMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("SystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_EquipmentDefinitions_SortOrder");

                    b.HasIndex("SystemType")
                        .HasDatabaseName("IX_EquipmentDefinitions_SystemType");

                    b.ToTable("EquipmentDefinitions", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.GeneralMemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("GeneralMemos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Institutions_Name");

                    b.ToTable("Institutions", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.InstitutionSystem", b =>
                {
                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<int>("SystemType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("InstitutionId", "SystemType");

                    b.HasIndex("SystemType")
                        .HasDatabaseName("IX_InstitutionSystems_SystemType");

                    b.ToTable("InstitutionSystems", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.InventoryDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LinkedEquipmentType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryDefinitions_DisplayName");

                    b.HasIndex("LinkedEquipmentType")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryDefinitions_LinkedEquipmentType")
                        .HasFilter("\"LinkedEquipmentType\" IS NOT NULL");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_InventoryDefinitions_SortOrder");

                    b.ToTable("InventoryDefinitions", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.InventorySerialCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("PhysicalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SerialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryDefinitionId")
                        .HasDatabaseName("IX_InventorySerialCodes_InventoryDefinitionId");

                    b.HasIndex("InventoryDefinitionId", "SerialCode")
                        .IsUnique()
                        .HasDatabaseName("IX_InventorySerialCodes_Definition_Code");

                    b.ToTable("InventorySerialCodes", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.LoanedEquipmentNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderLoanedEquipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderLoanedEquipmentId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("IX_LoanedEquipmentNotes_Line_Ordinal");

                    b.ToTable("LoanedEquipmentNotes", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.LostEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HebrewDate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_LostEquipments_CreatedAt");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_LostEquipments_Phone");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LostEquipments_Status");

                    b.ToTable("LostEquipments", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomReturnTime")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DepositOnName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DepositType")
                        .HasColumnType("integer");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReturnProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUnpaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ReturnTimeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("SystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UrgentBoardNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("IX_Orders_InstitutionId");

                    b.HasIndex("IsCancelled")
                        .HasDatabaseName("IX_Orders_IsCancelled");

                    b.HasIndex("IsUnpaid")
                        .HasDatabaseName("IX_Orders_IsUnpaid");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Orders_Phone");

                    b.HasIndex("Phone2")
                        .HasDatabaseName("IX_Orders_Phone2")
                        .HasFilter("\"Phone2\" IS NOT NULL");

                    b.HasIndex("SystemType")
                        .HasDatabaseName("IX_Orders_SystemType");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ManualUnreturnedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("InventoryDefinitionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LoanedEquipmentType")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ManualUnreturnedItems_CreatedAt");

                    b.HasIndex("InventoryDefinitionId")
                        .HasDatabaseName("IX_ManualUnreturnedItems_InventoryDefinitionId");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("IX_ManualUnreturnedItems_IsResolved");

                    b.HasIndex("ItemCode", "IsResolved")
                        .HasDatabaseName("IX_ManualUnreturnedItems_Code_Resolved");

                    b.ToTable("ManualUnreturnedItems", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderCustomMissingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MissingQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "IsResolved")
                        .HasDatabaseName("IX_OrderCustomMissingItems_Order_Resolved");

                    b.ToTable("OrderCustomMissingItems", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderEquipment", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrderId", "EquipmentDefinitionId");

                    b.HasIndex("EquipmentDefinitionId")
                        .HasDatabaseName("IX_OrderEquipments_EquipmentDefinitionId");

                    b.ToTable("OrderEquipments", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderLoanedEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomItemName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ExpectedNoteCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCustomItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("LoanedEquipmentType")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderLoanedEquipments_OrderId");

                    b.HasIndex("OrderId", "LoanedEquipmentType")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderLoanedEquipments_Order_Type_Unique")
                        .HasFilter("\"IsCustomItem\" = false");

                    b.ToTable("OrderLoanedEquipments", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderShift", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "OrderDate", "TimeSlot");

                    b.HasIndex("OrderDate", "TimeSlot")
                        .HasDatabaseName("IX_OrderShifts_Date_TimeSlot");

                    b.HasIndex("OrderDate", "TimeSlot", "OrderId")
                        .HasDatabaseName("IX_OrderShifts_Date_TimeSlot_OrderId");

                    b.ToTable("OrderShifts", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("IX_ToolDefinitions_DisplayName");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_ToolDefinitions_SortOrder");

                    b.ToTable("ToolDefinitions", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deposit")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HebrewLentDisplay")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("HebrewReturnedDisplay")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("IX_ToolLoans_InstitutionId");

                    b.HasIndex("LentAt")
                        .HasDatabaseName("IX_ToolLoans_LentAt");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_ToolLoans_Phone");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("IX_ToolLoans_ReturnedAt");

                    b.ToTable("ToolLoans", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolLoanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("HebrewReturnedDisplay")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ToolDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("ToolLoanId")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnedAt")
                        .HasDatabaseName("IX_ToolLoanItems_ReturnedAt");

                    b.HasIndex("SerialCode")
                        .HasDatabaseName("IX_ToolLoanItems_SerialCode");

                    b.HasIndex("ToolDefinitionId")
                        .HasDatabaseName("IX_ToolLoanItems_ToolDefinitionId");

                    b.HasIndex("ToolLoanId")
                        .HasDatabaseName("IX_ToolLoanItems_ToolLoanId");

                    b.ToTable("ToolLoanItems", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolSerialCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SerialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ToolDefinitionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToolDefinitionId")
                        .HasDatabaseName("IX_ToolSerialCodes_ToolDefinitionId");

                    b.HasIndex("ToolDefinitionId", "SerialCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ToolSerialCodes_ToolDefinitionId_SerialCode");

                    b.ToTable("ToolSerialCodes", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username_Unique");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("WaitlistDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SystemType")
                        .HasDatabaseName("IX_WaitlistEntries_SystemType");

                    b.HasIndex("WaitlistDate")
                        .HasDatabaseName("IX_WaitlistEntries_WaitlistDate");

                    b.HasIndex("EquipmentType", "WaitlistDate")
                        .HasDatabaseName("IX_WaitlistEntries_Equipment_Date");

                    b.ToTable("WaitlistEntries", (string)null);
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookCopy", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookLoanItem", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.BookLoan", "BookLoan")
                        .WithMany("Items")
                        .HasForeignKey("BookLoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookLoan");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.CustomerDebt", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.BookLoanItem", "BookLoanItem")
                        .WithOne("CustomerDebt")
                        .HasForeignKey("SoundRent.Api.Domain.Entities.CustomerDebt", "BookLoanItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoundRent.Api.Domain.Entities.ToolLoanItem", "ToolLoanItem")
                        .WithOne("CustomerDebt")
                        .HasForeignKey("SoundRent.Api.Domain.Entities.CustomerDebt", "ToolLoanItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookLoanItem");

                    b.Navigation("ToolLoanItem");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.CustomerSystem", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Customer", "Customer")
                        .WithMany("Systems")
                        .HasForeignKey("CustomerPhone1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.InstitutionSystem", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Institution", "Institution")
                        .WithMany("Systems")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.EquipmentDefaultAccessory", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.InventoryDefinition", "InventoryDefinition")
                        .WithMany()
                        .HasForeignKey("InventoryDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InventoryDefinition");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.InventorySerialCode", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.InventoryDefinition", "InventoryDefinition")
                        .WithMany("SerialCodes")
                        .HasForeignKey("InventoryDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryDefinition");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.LoanedEquipmentNote", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.OrderLoanedEquipment", "OrderLoanedEquipment")
                        .WithMany("Notes")
                        .HasForeignKey("OrderLoanedEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderLoanedEquipment");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Order", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Institution", "Institution")
                        .WithMany("Orders")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ManualUnreturnedItem", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.InventoryDefinition", "InventoryDefinition")
                        .WithMany()
                        .HasForeignKey("InventoryDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InventoryDefinition");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderCustomMissingItem", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Order", "Order")
                        .WithMany("CustomMissingItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderEquipment", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.EquipmentDefinition", "EquipmentDefinition")
                        .WithMany("Orders")
                        .HasForeignKey("EquipmentDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoundRent.Api.Domain.Entities.Order", "Order")
                        .WithMany("Equipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentDefinition");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderLoanedEquipment", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Order", "Order")
                        .WithMany("LoanedEquipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderShift", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Order", "Order")
                        .WithMany("Shifts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolLoan", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.Institution", "Institution")
                        .WithMany("ToolLoans")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolLoanItem", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.ToolLoan", "ToolLoan")
                        .WithMany("Items")
                        .HasForeignKey("ToolLoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolLoan");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolSerialCode", b =>
                {
                    b.HasOne("SoundRent.Api.Domain.Entities.ToolDefinition", "ToolDefinition")
                        .WithMany("SerialCodes")
                        .HasForeignKey("ToolDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolDefinition");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookLoan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.BookLoanItem", b =>
                {
                    b.Navigation("CustomerDebt");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Systems");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.EquipmentDefinition", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Institution", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Systems");

                    b.Navigation("ToolLoans");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.InventoryDefinition", b =>
                {
                    b.Navigation("SerialCodes");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.Order", b =>
                {
                    b.Navigation("CustomMissingItems");

                    b.Navigation("Equipments");

                    b.Navigation("LoanedEquipments");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.OrderLoanedEquipment", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolDefinition", b =>
                {
                    b.Navigation("SerialCodes");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolLoan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SoundRent.Api.Domain.Entities.ToolLoanItem", b =>
                {
                    b.Navigation("CustomerDebt");
                });
#pragma warning restore 612, 618
        }
    }
}
